<a href="https://colab.research.google.com/github/meetgandhi123/PyTorch-Basic-Concepts/blob/main/00_PyTorch_Basic_Syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic Initialization


*   Empty Tensor
*   Zero Tensor
*   Ones Tensor
*   Getting Data Type
*   Getting size

In [1]:
import torch

In [2]:
x = torch.empty(1, dtype=torch.int)
print(x)

tensor([387677760], dtype=torch.int32)


In [3]:
x = torch.zeros(1, dtype=torch.int)
print(x)

tensor([0], dtype=torch.int32)


In [4]:
x = torch.ones(1, dtype=torch.int)
print(x)

tensor([1], dtype=torch.int32)


In [5]:
x.dtype

torch.int32

In [6]:
x.size()

torch.Size([1])

##Inplace Operation

In [ ]:
y = torch.rand(2)
x = torch.rand(2)
print(x,y)
y.add_(x)
print(y)

## Conversion 

*   List to Tensor
*   Numpy to Tensor and visa versa



In [7]:
# List to Tensor
l=[1,2,3]
x = torch.tensor(l)
print(x.dtype)

torch.int64


In [8]:
# Numpy to Tensor
import numpy as np

a=np.ones(5)
b=torch.from_numpy(a)
print(b.dtype)

# Tensor to Numpy
a=torch.rand(5)
b=a.numpy()
print(type(b))

torch.float64
<class 'numpy.ndarray'>


## Reshape

In [9]:
x = torch.rand(10)

y = x.view(2,5)
print(y.size())

z = x.view(-1,5)
print(z.size())

torch.Size([2, 5])
torch.Size([2, 5])


## Autograd

In [10]:
x = torch.rand(3, requires_grad=True)

y=x+2
z=y*y*2

# Here using the mean functio we are converting [1,3] 
# size tensor to [1,1]
z=z.mean()

z.backward()
print(x.grad)

tensor([3.0104, 3.8702, 2.7725])


In [11]:
x = torch.rand(3, requires_grad=True)

y=x+2
z=y*y*2

# If we are not conversting it in a scalor value
# then we need to pass a tensor to compute backward()

v=torch.tensor([1.0,0.1,0.01],dtype=torch.float32)

z.backward(v)
print(x.grad)

tensor([11.9812,  0.8899,  0.0870])


How to prevent backpropogation.
1.   requires_grad_(False)
2.   .detach()
3.   with torch.no_grad():



In [12]:
# 1. requires_grad(False)
x= torch.ones(5, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
tensor([1., 1., 1., 1., 1.])


In [13]:
# 2. detach()
x= torch.ones(5, requires_grad=True)
print(x)
y=x.detach()
print(y)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
tensor([1., 1., 1., 1., 1.])


In [14]:
# 3. with torch.no_grad()
x= torch.ones(5, requires_grad=True)
with torch.no_grad():
  y=x+2
  print(y)

tensor([3., 3., 3., 3., 3.])
