<a href="https://colab.research.google.com/github/meetgandhi123/PyTorch-Basic-Concepts/blob/main/Saving_and_Loading_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Method 1

Save Model.

In [4]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features,1)

    def forward(self,x):
        return torch.sigmoid(self.linear(x))

model = Model(n_input_features=10)
# training of your model...

FILE = "model_method1.pth"
torch.save(model,FILE)

for params in model.parameters():
    print(params)

Parameter containing:
tensor([[-0.0503, -0.0934, -0.1071,  0.2120,  0.1271,  0.1475,  0.0065, -0.0234,
         -0.3010, -0.0805]], requires_grad=True)
Parameter containing:
tensor([-0.2222], requires_grad=True)


Load Model

In [5]:
import torch
import torch.nn as nn

FILE = "/content/model_method1.pth"

loaded_model = torch.load(FILE)
loaded_model.eval()

for params in loaded_model.parameters():
    print(params)

Parameter containing:
tensor([[-0.0503, -0.0934, -0.1071,  0.2120,  0.1271,  0.1475,  0.0065, -0.0234,
         -0.3010, -0.0805]], requires_grad=True)
Parameter containing:
tensor([-0.2222], requires_grad=True)


## Method 2 (Recommended) 

Save Model.

In [7]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features,1)

    def forward(self,x):
        return torch.sigmoid(self.linear(x))

model = Model(n_input_features=10)
# training of your model...

FILE = "model_method2.pth"
torch.save(model.state_dict(),FILE)

#print(model.state_dict())
#OrderedDict([('linear.weight', tensor([[ 0.2519,  0.2721, -0.0873, -0.0048,  0.1739, -0.1456,  0.2998, -0.1276,
#          0.0670,  0.2060]])), ('linear.bias', tensor([-0.1913]))])

for params in model.parameters():
    print(params)

Parameter containing:
tensor([[ 0.2519,  0.2721, -0.0873, -0.0048,  0.1739, -0.1456,  0.2998, -0.1276,
          0.0670,  0.2060]], requires_grad=True)
Parameter containing:
tensor([-0.1913], requires_grad=True)


Load Model.

In [8]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features,1)

    def forward(self,x):
        return torch.sigmoid(self.linear(x))

FILE = "/content/model_method2.pth"

loaded_model = Model(n_input_features=10)
loaded_model.load_state_dict(torch.load(FILE))

loaded_model.eval()

for params in loaded_model.parameters():
    print(params)

Parameter containing:
tensor([[ 0.2519,  0.2721, -0.0873, -0.0048,  0.1739, -0.1456,  0.2998, -0.1276,
          0.0670,  0.2060]], requires_grad=True)
Parameter containing:
tensor([-0.1913], requires_grad=True)


## Saving optimizers along with model in checkpoint file.

Save checkpoint.

In [11]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,n_input_features):
        super(Model,self).__init__()
        self.linear = nn.Linear(n_input_features,10)

    def forward(self,x):
        return torch.sigmoid(self.linear(x))
    
model = Model(n_input_features=10)

learning_rate = 0.001
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#print(optimizer.state_dict())
#{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [0, 1]}]}

checkpoint = {
    "epoch" : 5,
    "model_state" : model.state_dict(),
    "optimizer_state" : optimizer.state_dict() 
}

torch.save(checkpoint,"checkpoint.pth")

Load Checkpoint.

In [12]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,n_input_features):
        super(Model,self).__init__()
        self.linear = nn.Linear(n_input_features,10)

    def forward(self,x):
        return torch.sigmoid(self.linear(x))
    
loaded_checkpoint = torch.load("/content/checkpoint.pth")

epoch = loaded_checkpoint["epoch"]
loaded_model = Model(n_input_features=10)
loaded_optimizer = torch.optim.SGD(loaded_model.parameters(), lr=0)

loaded_model.load_state_dict(checkpoint["model_state"])
loaded_optimizer.load_state_dict(checkpoint["optimizer_state"])

#print(optimizer.state_dict())
#{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [0, 1]}]}

{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [0, 1]}]}


## Save model on GPU and Load it on CPU

In [ ]:
import torch
import torch.nn as nn

# Save model on GPU
device = torch.device("cuda")
model.to(device)
torch.save(model.save_dict(), PATH)

# Load model on CPU
device = torch.device("cpu")
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))

## Save model on GPU and Load it on GPU

In [ ]:
import torch
import torch.nn as nn

# Save model on GPU
device = torch.device("cuda")
model.to(device)
torch.save(model.save_dict(), PATH)

# Load model on GPU
device = torch.device("cuda")

model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))
model.to(device)

## Save model on CPU and Load it on GPU

In [ ]:
import torch
import torch.nn as nn

# Save model on CPU
torch.save(model.save_dict(), PATH)

# Load model on GPU
device = torch.device("cuda")

model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location="cuda:0")) # GPU device number.
model.to(device)